### ISSUE TITLE
[FEATURE] Shamir's Secret Sharing System

### ISSUE THREAD

**Issue by quantum9Innovation** [Quantalabs/DiffPriv#14]
**Is your feature request related to a problem? Please describe.**
No relation to any problems.

**Describe the solution you'd like**
See https://en.wikipedia.org/wiki/Shamir's_Secret_Sharing for implementation details.

**Additional context**
See the #feat-sss branch for current progress. PR incoming.

**Comment by Quantalabs** [comment]
See #17
